# Builds the project and publishes to NPM.
# Before the publish, in package.json, the string MINORVERSION is replaced by the build number.

name: bigformmenu-publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install

      - name: Make dist directory
        run: mkdir -vp dist

      - name: tsc
        uses: icrawl/action-tsc@v1
        with:
          project: bigformmenu

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: bigformmenu/bigformmenu.scss
          destination: dist/bigformmenu.css

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPMPUBLISHTOKEN }}

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"



